### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by hhayano** [wndhydrnt/go-signature-statusbar#22]
[Enter steps to reproduce:]

1. get the Cannot read property 'openScopes' of undefined described in https://github.com/atom/bracket-matcher/issues/292
2. disable bracket-matcher
3. quit atom
3. open atom using `atom .`

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [go-signature-statusbar](https://github.com/wndhydrnt/go-signature-statusbar) package 1.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/hayanoh/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:117

TypeError: Cannot read property 'match' of undefined
    at GoSignatureStatusbarView.extractFunc (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:117:23)
    at GoSignatureStatusbarView.displaySignature (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:49:21)
    at GoSignatureStatusbarView.activate (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:25:12)
    at /packages/go-signature-statusbar/lib/go-signature-statusbar.js:30:39
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:493:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:339:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:492:27)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
go-debug 1.5.0 
go-plus 5.5.5 
go-signature-statusbar 1.2.1 
hyperclick 0.1.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.3 
```

**Comment by hhayano** [comment]
Can't seem to reproduce the error, so I'm closing the issue.

**Comment by Vrakfall** [comment]
It just happened to me after restarting Atom and when trying to open a file which I changed the path when Atom was closed.
I guess it's just a tab referring to a not found file that triggers this issue (at least for my case).

**Edit:** Yep, just got the same for another file.

**Comment by antony66** [comment]
Same problem here. I get this error every time I start atom. Even after the package go-signature-statusbar got update today.
UPD: looks like this happened because one of my opened tabs contained previously deleted file.

**Comment by mmcloughlin** [comment]
I'm seeing the same behavior as @antony66. In my case I switched git branches, so some of the files I had open in tabs had disappeared.

**Comment by wndhydrnt** [comment]
I've been able to reproduce it this way:

1. Open at least two go files in tabs
2. Point the cursor in one of the tabs to a function so that it gets displayed in the status bar
3. Choose the other tab
4. Right-click on the other tab and choose "Close All Tabs"

It looks like it is related to the debounce introduced in v1.2.2. I'll have a look.
