### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLastCursor' of undefined

### ISSUE THREAD

**Issue by rippy** [wndhydrnt/go-signature-statusbar#23]
[Enter steps to reproduce:]

1. I think what triggered this was an upgrade to 1.19.4 from an older version of Atom after I had installed this plugin.  Not 100% sure though; since Atom asked me to file this here we are.

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [go-signature-statusbar](https://github.com/wndhydrnt/go-signature-statusbar) package 1.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getLastCursor' of undefined

```
At /home/user/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:50

TypeError: Cannot read property 'getLastCursor' of undefined
    at GoSignatureStatusbarView.displaySignature (/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:50:26)
    at invokeFunc (/packages/go-signature-statusbar/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/packages/go-signature-statusbar/node_modules/lodash.debounce/index.js:207:14)
    at timerExpired (/packages/go-signature-statusbar/node_modules/lodash.debounce/index.js:195:14)
```

### Commands

```
     -0:45.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:42.5.0 golang:update-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-typescript 11.0.7 
autoclose-html 0.23.0 
busy-signal 1.4.3 
code-peek 1.4.21 
color-picker 2.2.5 
color-tabs 0.1.8 
color-tabs-regex 0.2.5 
double-tag 0.9.0 
environment 1.3.1 
file-icons 2.1.11 
go-debug 1.5.0 
go-outline 0.6.6 
go-plus 5.5.5 
go-rename 0.3.0 
go-signature-statusbar 1.2.2 
haxe 0.8.14 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
language-docker 1.1.8 
language-glsl 2.0.1 
language-gradle 0.0.3 
language-haxe 0.6.0 
language-nimrod 0.1.0 
language-opencl 0.1.1 
language-pony 0.3.8 
language-powershell 4.0.0 
language-restructuredtext 1.1.0 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-javac 1.9.4 
linter-jshint 3.1.5 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-pigments 0.2.2 
pigments 0.40.2 
sort-lines 0.15.0 
symbol-gen 1.3.1 
sync-settings 0.8.3 
```

**Comment by asamek** [comment]
I have same issue. For me it appears after updating Atom from 1.19.2 to 1.19.4. Stack trace:

```
/Users/user/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:50

TypeError: Cannot read property 'getLastCursor' of undefined
    at GoSignatureStatusbarView.displaySignature (/Users/user/.atom/packages/go-signature-statusbar/lib/go-signature-statusbar-view.js:50:26)
    at invokeFunc (/Users/user/.atom/packages/go-signature-statusbar/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/Users/user/.atom/packages/go-signature-statusbar/node_modules/lodash.debounce/index.js:207:14)
    at timerExpired (/Users/user/.atom/packages/go-signature-statusbar/node_modules/lodash.debounce/index.js:195:14)
```
